# Generated by Django 5.1.7 on 2025-03-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyupdate',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
