# Generated by Django 5.1.7 on 2025-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weeklyupdate_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyupdate',
            name='bmi_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
