# Generated by Django 5.1.7 on 2025-03-16 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weeklyupdate_bmi_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessCoachFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Excellent')], default=3)),
                ('recommendation', models.CharField(choices=[('Increase Protein', 'Increase Protein'), ('Reduce Sugar', 'Reduce Sugar'), ('Improve Hydration', 'Improve Hydration'), ('More Vegetables', 'More Vegetables'), ('Balanced Diet', 'Balanced Diet')], max_length=255)),
                ('date_provided', models.DateTimeField(auto_now_add=True)),
                ('bmi_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.weeklyupdate')),
                ('coach', models.ForeignKey(limit_choices_to={'groups__name': 'Wellness Coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('food_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dailyfoodlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
